ci: Split build into 2 jobs and upload .tar.gz for ios instead of the rest

diff --git a/.github/workflows/beta.yml b/.github/workflows/beta.yml
--- a/.github/workflows/beta.yml
+++ b/.github/workflows/beta.yml
@@ -5,34 +5,13 @@ on:
     tags:
       - 'beta-*'
 
-  workflow_dispatch:
-    inputs:
-      platform:
-        description: "Plateforme à builder"
-        required: true
-        default: all
-        type: choice
-        options:
-          - all
-          - android
-          - ios
-      create_release:
-        description: "Créer une release GitHub ?"
-        required: true
-        default: "false"
-        type: choice
-        options:
-          - "true"
-          - "false"
-
 jobs:
-  build:
-    name: Build application
+  build_android:
+    name: Build Android application
     runs-on: ubuntu-latest
 
     outputs:
       ANDROID_URL: ${{ steps.check.outputs.ANDROID_URL }}
-      IOS_URL: ${{ steps.check.outputs.IOS_URL }}
 
     steps:
       - uses: actions/checkout@v4
@@ -42,7 +21,6 @@ jobs:
       - uses: actions/setup-node@v4
         with:
           node-version: 20.x
-          cache: npm
 
       - name: Setup Expo and EAS
         uses: expo/expo-github-action@v8
@@ -53,40 +31,67 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Start EAS Build
-        run: |
-          PLATFORM=${{ github.event.inputs.platform || 'all' }}
-          eas build --platform "$PLATFORM" --profile development --non-interactive --wait --json > build-info.json
+      - name: Start EAS Android build
+        run: eas build --platform android --profile development --non-interactive --wait --json > build-info.json
 
-      - name: Check build results and store URLs
+      - name: Check build result and store URL
         id: check
         run: |
-          PLATFORM=${{ github.event.inputs.platform || 'all' }}
+          status=$(jq -r '.[] | select(.platform == "ANDROID") | .status' build-info.json)
 
-          get_url() {
-            local platform=$1
-
-            local status=$(jq -r --arg PLATFORM "$platform" '.[] | select(.platform == ($PLATFORM | ascii_upcase)) | .status' build-info.json)
-            if [[ "$status" != "FINISHED" ]]; then
-              echo "❌ Build $platform failed!"
-              exit 1
-            fi
-
-            local url=$(jq -r --arg PLATFORM "$platform" '.[] | select(.platform == ($PLATFORM | ascii_upcase)) | .artifacts.buildUrl' build-info.json)
-            echo "${platform^^}_URL=$url" >> $GITHUB_OUTPUT
-          }
-
-          if [[ "$PLATFORM" == "all" || "$PLATFORM" == "android" ]]; then
-            get_url android
+          if [[ "$status" != "FINISHED" ]]; then
+            echo "❌ Android build failed !"
+            exit 1
           fi
-          if [[ "$PLATFORM" == "all" || "$PLATFORM" == "ios" ]]; then
-            get_url ios
+
+          url=$(jq -r '.[] | select(.platform == "ANDROID") | .artifacts.buildUrl' build-info.json)
+          echo "ANDROID_URL=$url" >> $GITHUB_OUTPUT
+
+  build_ios:
+    name: Build iOS application
+    runs-on: ubuntu-latest
+
+    outputs:
+      IOS_URL: ${{ steps.check.outputs.IOS_URL }}
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20.x
+
+      - name: Setup Expo and EAS
+        uses: expo/expo-github-action@v8
+        with:
+          eas-version: latest
+          token: ${{ secrets.EXPO_TOKEN }}
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Start EAS iOS build
+        run: eas build --platform ios --profile development --non-interactive --wait --json > build-info.json
+
+      - name: Check build result and store URL
+        id: check
+        run: |
+          status=$(jq -r '.[] | select(.platform == "IOS") | .status' build-info.json)
+
+          if [[ "$status" != "FINISHED" ]]; then
+            echo "❌ iOS build failed !"
+            exit 1
           fi
+
+          url=$(jq -r '.[] | select(.platform == "IOS") | .artifacts.buildUrl' build-info.json)
+          echo "IOS_URL=$url" >> $GITHUB_OUTPUT
 
   changelog:
     name: Generate changelog
     runs-on: ubuntu-latest
-    needs: build
+    needs: [build_android, build_ios]
 
     outputs:
       CHANGELOG_BODY: ${{ steps.changelog.outputs.changes }}
@@ -105,14 +110,14 @@ jobs:
           excludeTypes: ""
 
   release:
-    name: Create GitHub Release
+    name: Create GitHub release
     runs-on: ubuntu-latest
-    needs: [build, changelog]
+    needs: [build_android, build_ios, changelog]
     if: ${{ github.event.inputs.create_release == 'true' || github.event_name == 'push' }}
 
     steps:
       - uses: actions/checkout@v4
-  
+
       - name: Download and package artifacts
         id: package
         run: |
@@ -121,21 +126,20 @@ jobs:
 
           FILES=()
 
-          if [[ -n "${{ needs.build.outputs.ANDROID_URL }}" ]]; then
-            curl -L "${{ needs.build.outputs.ANDROID_URL }}" -o "${ANDROID_FILE_NAME}.apk"
+          if [[ -n "${{ needs.build_android.outputs.ANDROID_URL }}" ]]; then
+            curl -L "${{ needs.build_android.outputs.ANDROID_URL }}" -o "${ANDROID_FILE_NAME}.apk"
             zip "${ANDROID_FILE_NAME}.zip" "${ANDROID_FILE_NAME}.apk"
             FILES+=("${ANDROID_FILE_NAME}.apk" "${ANDROID_FILE_NAME}.zip")
           fi
 
-          if [[ -n "${{ needs.build.outputs.IOS_URL }}" ]]; then
-            curl -L "${{ needs.build.outputs.IOS_URL }}" -o "${IOS_FILE_NAME}.ipa"
-            zip "${IOS_FILE_NAME}.zip" "${IOS_FILE_NAME}.ipa"
-            FILES+=("${IOS_FILE_NAME}.ipa" "${IOS_FILE_NAME}.zip")
+          if [[ -n "${{ needs.build_ios.outputs.IOS_URL }}" ]]; then
+            curl -L "${{ needs.build_ios.outputs.IOS_URL }}" -o "${IOS_FILE_NAME}.tar.gz"
+            FILES+=("${IOS_FILE_NAME}.tar.gz")
           fi
 
           echo "files=${FILES[*]}" >> $GITHUB_OUTPUT
 
-      - name: Upload to GitHub Release
+      - name: Upload to GitHub release
         uses: softprops/action-gh-release@v2
         with:
           generate_release_notes: true
